project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://<Imani0830>.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
        - text: "Project 1: Transit"
          href: mp01.qmd
format:
  html:
    theme: solar
    toc: false

editor:
  mode: source
  
  